# Multi-Tenant SaaS Platform - Local Development Environment
# Docker Compose configuration for local PostgreSQL database

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas-platform-postgres
    environment:
      POSTGRES_DB: saas_platform
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saas_user -d saas_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saas-network

volumes:
  postgres_data:
    driver: local

networks:
  saas-network:
    driver: bridge
