# Local Development Configuration
# Activate this profile with: --spring.profiles.active=local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_platform
    username: saas_user
    password: saas_password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

# Disable OAuth2 for local development (optional)
# spring:
#   autoconfigure:
#     exclude: org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

# Logging - More verbose for local development
logging:
  level:
    root: INFO
    com.platform.saas: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# CORS - Allow all origins for local development
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
